- name: Add user to group
  hosts: all

  tasks:
    - name: Linux group add
      user:
        name: "{{ user }}"
        groups: "{{ group }}"
        append: yes
      become: yes
      when: ansible_os_family != "Windows"

    # --- Windows Specific Tasks ---
    
    - name: Ensure Windows group exists
      win_group:
        name: "{{ group }}"
        state: present
      when: ansible_os_family == "Windows"

    - name: Windows group add member
      win_group_membership:
        name: "{{ group }}"
        members:
          - "{{ user }}"
        state: present
      when: ansible_os_family == "Windows"
