# primitives/add_to_group.yml
- name: Add user to group
  hosts: all
  become: yes

  tasks:
    - name: Linux group add
      user:
        name: "{{ user }}"
        groups: "{{ group }}"
        append: yes
      when: ansible_os_family != "Windows"

    - name: Windows group add
      win_group_membership:
        name: "{{ group }}"
        members:
          - "{{ user }}"
        state: present
      when: ansible_os_family == "Windows"