- name: Grant admin privileges
  hosts: all
  

  tasks:
    - name: Linux sudo access
      lineinfile:
        path: "/etc/sudoers.d/{{ user }}"
        line: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
        create: yes
        mode: '0440'
        validate: "visudo -cf %s"
      become: yes  # Only trigger sudo on Linux
      when: ansible_os_family != "Windows"

    - name: Windows admin access
      win_group_membership:
        name: Administrators
        members:
          - "{{ user }}"
        state: present
      # No become needed for Windows; your winrm user is already an Admin
      when: ansible_os_family == "Windows"
