# primitives/lock_user.yml
- name: Lock user
  hosts: all
  become: yes

  tasks:
    - name: Linux lock
      command: "passwd -l {{ user }}"
      when: ansible_os_family != "Windows"

    - name: Windows disable user
      win_user:
        name: "{{ user }}"
        account_disabled: yes
      when: ansible_os_family == "Windows"