# primitives/set_password.yml
- name: Set password
  hosts: all
  become: yes

  tasks:
    - name: Linux password
      user:
        name: "{{ user }}"
        password: "{{ password_hash }}"
      when: ansible_os_family != "Windows"

    - name: Windows password
      win_user:
        name: "{{ user }}"
        password: "{{ password }}"
      when: ansible_os_family == "Windows"