# primitives/unlock_user.yml
- name: Unlock user
  hosts: all
  become: yes

  tasks:
    - name: Linux unlock
      command: "passwd -u {{ user }}"
      when: ansible_os_family != "Windows"

    - name: Windows enable user
      win_user:
        name: "{{ user }}"
        account_disabled: no
      when: ansible_os_family == "Windows"