[linux_lab]
linux-pc-01 ansible_host=192.168.1.101 ansible_user=labadmin ansible_ssh_private_key_file=~/.ssh/lab_key
linux-pc-02 ansible_host=192.168.1.102 ansible_user=labadmin ansible_ssh_private_key_file=~/.ssh/lab_key
linux-pc-03 ansible_host=192.168.1.103 ansible_user=labadmin ansible_ssh_private_key_file=~/.ssh/lab_key


[windows_lab]
win-pc-01 ansible_host=192.168.1.111 ansible_user=Administrator ansible_password=YourWinPassword ansible_connection=winrm ansible_winrm_transport=basic ansible_winrm_server_cert_validation=ignore
win-pc-02 ansible_host=192.168.1.112 ansible_user=Administrator ansible_password=YourWinPassword ansible_connection=winrm ansible_winrm_transport=basic ansible_winrm_server_cert_validation=ignore
windows-main ansible_host=192.168.56.1 ansible_user=Administrator ansible_password=Password123! ansible_connection=winrm ansible_winrm_transport=basic ansible_winrm_server_cert_validation=ignore ansible_port=5985 ansible_become_method=runas

[backup_server]
backup-srv ansible_host=192.168.1.200 ansible_user=backup_admin ansible_ssh_private_key_file=~/.ssh/lab_key
backup-srv ansible_host=127.0.0.1 ansible_connection=local

[lab:children]
linux_lab
windows_lab

[lab:vars]
backup_server_ip=192.168.1.200
backup_server_user=backup_admin
backup_base_path=/mnt/backups
backup_server_ip=192.168.56.101
backup_server_user=labadmin
backup_base_path=/home/labadmin/backups

[local]
localhost ansible_connection=local

[kali_machine]
kali_pc ansible_host=192.168.1.16 ansible_user=kali ansible_password=kali

[all:vars]
# This tells Ansible to use standard SSH for Linux machines
ansible_connection=ssh
# Use this if you haven't set up SSH keys yet
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
